### ISSUE TITLE
JavaScript error on downloading screenshots

### ISSUE THREAD

**Issue by tatoribas2012** [RedDuckss/CemUI#43]
![screenshot_3](https://user-images.githubusercontent.com/31782204/30233686-7c66287c-94cd-11e7-90ee-1b9fdb05f237.png)

**Comment by RedDuckss** [comment]
Could you provide a list of your games, the rom types (RPX, WUD, WUX, etc), and your game folder structure?

**Comment by tatoribas2012** [comment]
It just fixed itself for some reason now lol, it works now. Thanks!

**Comment by RedDuckss** [comment]
Even so, the error did occur and the line it happens on is part of the game data downloading function. I would still like to have the information I requested in my previous comment so that I can look into the issue further, and patch it completely so it doesn't happen again.

**Comment by tatoribas2012** [comment]
*Could you Prove a list of your games?
>Captain Toad Treasure Tracker
>Super Mario 3D World
>Super smash bros 4
>Breath of the Wild
>Wind Waker

*Specify Rom Types
They're all RPX.

*Game folder structure
D:\CEMU (Files)\Games

**Comment by RedDuckss** [comment]
Perfect, thank you!

**Comment by RedDuckss** [comment]
Cannot replicate issue however I have made the needed changes to the lines mentioned in the error, so hopefully it is fixed. Feel free to reopen if the error happens again

**Comment by SKYCrap** [comment]
Hey, Unfortunatelly, i have the same problem, but it is not fixed yet:/

**Comment by RedDuckss** [comment]
Does it happen regularly or only once in a while? And are you using the latest _build_ it the latest _source code_?

**Comment by SKYCrap** [comment]
regulary. Downloaded 2.0.0 alpha 1, but also don't work on every version i tried, even dev

**Comment by RedDuckss** [comment]
RPX rom? If it's an RPX rom send me a zip file of the `meta` folder for the game so I can grab the title id. Also send a screenshot of the error you are getting, since it might be different than the exact error here (use the latest dev version, not the latest build)

**Comment by SKYCrap** [comment]
[meta.zip](https://github.com/RedDuckss/CemUI/files/1290742/meta.zip)

**Comment by SKYCrap** [comment]
https://i.gyazo.com/9df6fe79d09688eb54d24d6cb0ce6fae.png

**Comment by RedDuckss** [comment]
Please try again using the latest dev version and send a screenshot of _that_ error. The error in that screenshot is from the latest built version, which I said before does not contain the changes I made for this issue.

**Comment by SKYCrap** [comment]
https://i.gyazo.com/3fe4d8e0c7137188e7edc91e0b5eef24.png

**Comment by RedDuckss** [comment]
I just pushed a small update that will log when that error occurs, please try once more with the new latest dev version and if the error happens again, screenshot the log. The error is being thrown due to a request error.

**Comment by SKYCrap** [comment]
Error :(
![image](https://user-images.githubusercontent.com/24544265/30251460-015913c6-9679-11e7-914a-8bb6377e5e17.png)

**Comment by RedDuckss** [comment]
I asked for the log this time, not the error. Check cmd for the log

**Comment by SKYCrap** [comment]
oops, sorry, wait a minute

**Comment by SKYCrap** [comment]
Uhm, cant find log, what cmd exactly ?

**Comment by RedDuckss** [comment]
cmd is the command prompt, it's what you've been using to start CemUI in dev mode. Check that window.

**Comment by SKYCrap** [comment]
Nothing in command prompt after error 
![image](https://user-images.githubusercontent.com/24544265/30251529-8646dda6-967a-11e7-9180-1f34fe8ff0e6.png)

**Comment by SKYCrap** [comment]
hm, i see

**Comment by RedDuckss** [comment]
You see what (sorry, going through the code trying to figure out why it isn't logging)?

**Comment by SKYCrap** [comment]
Just used command electron without . , but it doesn't show log

**Comment by RedDuckss** [comment]
Try the latest dev version again. I added some missing `return`s that may have been the cause.

**Comment by SKYCrap** [comment]
Nope, not working, the same error

**Comment by RedDuckss** [comment]
Try once more. I went away from writing my own async loop handler to an async.each. If the error occurs send a screenshot as the line numbers have changed

**Comment by SKYCrap** [comment]
i just type npm i to update?

**Comment by RedDuckss** [comment]
No. npm is for package management in NodeJS, not the source code here. Is that what you've been doing? You need to manually re-clone the source code to get the latest dev version.

**Comment by SKYCrap** [comment]
S**t
Yep, just typing npm

**Comment by RedDuckss** [comment]
Ahh okay, now it's starting to make sense. Progress! At least now I know why it wasn't logging earlier

**Comment by SKYCrap** [comment]
![image](https://user-images.githubusercontent.com/24544265/30251677-0d1db540-967e-11e7-88c7-175a3304b7fd.png)
I'm sorry:/

**Comment by RedDuckss** [comment]
Don't be sorry. I can't replicate these errors so I'm actually unable to test my changes, so if anyone should be sorry it's me for using you as a test subject xD

I know why that error happened. To prevent spamming of this issue though (because its getting to that point) would you mind joining the Discord server in the `README` of the repo, and then DMing me? We can talk better there.

**Comment by PedgeJameson** [comment]
Can you gimme the DISACOR address, I am having the same error and then downloading game data just hangs.

**Comment by PedgeJameson** [comment]
DISCORD

**Comment by RedDuckss** [comment]
Have you tried any of the above solutions. Try the above solutions first

**Comment by PedgeJameson** [comment]
Whats the links to the dev builds

**Comment by RedDuckss** [comment]
There is no dev build. The developer version is the source code, running without being built

**Comment by PedgeJameson** [comment]
i dont understand what you mean, can you gimme a quick rundown of what I should do?

**Comment by PedgeJameson** [comment]
I dont understand, and I dont know how to build source code.

**Comment by PedgeJameson** [comment]
is the newest version not the source code? WIll someone help me?

**Comment by RedDuckss** [comment]
I’m not entirely sure how to explain it to you. The source code is the code on this repo. The entire point of a GitHub repo is to hold source code. The source code is in the master branch of the repo. You do not need to build it to run in dev mode

**Comment by MrIlliteracy** [comment]
@PedgeJameson 

I'll take over here for @RedDuckss because he's at work right now. The [releases](https://github.com/RedDuckss/CemUI/releases) section has pre-built (non-latest) versions of CemUI. 

CemUI is not built every time a change is made, so if you want the **absolute** newest version you'll have to build it yourself from the source code. The source code is what's found [here](https://github.com/RedDuckss/CemUI).

You can build it yourself by performing the steps in the readme, which can be found [here](https://github.com/RedDuckss/CemUI#how-to-get-the-latest-version-of-cemui).

**Comment by PedgeJameson** [comment]
That's just kind of odd, why run source code in an emulated
environment when you can just release nightly builds like most people? To
each their own, I just have never heard of it. Is it so there's not 60
million builds for an error that breaks more after it fixes one thing?

**Comment by MrIlliteracy** [comment]
Emulated environment? The application is going to be the same no matter who builds it.

We don't need to release nightly builds when the users can just do it themselves whenever they want. Nightly builds are more useful for closed-source applications because the users *can't* build it themselves.

Maybe you don't understand what I mean by "build"?

**Comment by PedgeJameson** [comment]
Ok you mean I can test in the linked program and if it works what happens
next?

**Comment by MrIlliteracy** [comment]
If you built the latest version from source and the bug no longer occurs then that means we fixed it 😄

**Comment by PedgeJameson** [comment]
So we report the bug, you make the source, we built it they will come. P

**Comment by MrIlliteracy** [comment]
Yes, users report bugs, we fix them.

**Comment by RedDuckss** [comment]
You don’t even have to build the source. You can download and run the source as-is. It will run exactly the same as a built version. The only difference is that running from source gives you the console and you have to start the program from cli

**Comment by PedgeJameson** [comment]
Yeah, thats kinda what I meant by "emulation" running it without it being
built using the J software. :P
So how do we report the errors to you, is there a log as we are running it
straight from the source?

**Comment by MrIlliteracy** [comment]
Please see [this part of the readme](https://github.com/RedDuckss/CemUI#i-found-a-bug).

**Comment by PedgeJameson** [comment]
thx

**Comment by RedDuckss** [comment]
```
Yeah, thats kinda what I meant by "emulation" running it without it being
built using the J software.
```
What exactly do you mean by this? Nothing is being emulated. It's an Electron app, the source code is literally the exact same as the built version. Unpacking the app.asar (which isn't even a compiled version of the code, it's just a fancy compressed file like a zip) will show you the exact same source as here. So it isn't being emulated, it's just running the app out of the asar and with the dev console.

```
built using the J software
```
Nothing is being built, and what is "J software"? I think you're confused on how a lot of things work here.

```
So how do we report the errors to you, is there a log as we are running it
straight from the source?
```
The dev console logs all Node errors, JavaScript exceptions throw a popup with the error details, and there's an error.log file in the most recent versions as well.

**Comment by PedgeJameson** [comment]
No offense but I'll wait until CEMU has a built in library. Too much work. Also, I just make shortcuts to the core files into a "games" folder. But...good luck!!

**Comment by MrIlliteracy** [comment]
A built-in library? Like it comes with games?

**Comment by PedgeJameson** [comment]
I mean a built launcher, that scans the games. This will be moot. Don't get all pissy.

**Comment by PedgeJameson** [comment]
Do you guys even have the blessing of CEMU? If so I will apologize. But it seems to me you are making releases and having users run them under source code as testers.

**Comment by RedDuckss** [comment]
No one is getting pissy lol (at least I'm not). However CemUI does what you described. It scans the games and does everything automatically. The only reason why there's extra steps _here_ is because the steps are for the _unstable developer version_

```
Do you guys even have the blessing of CEMU?
```
Why would we need any blessing from Cemu? And what gives Cemu any authority to even "bless" things.

```
But it seems to me you are making releases and having users run them under source code as testers.
```
_The current releases are alpha builds. The full release of CemUI isn't even out. And the developer version is specifically for testing_. We release alpha versions and ask people who have issues to try the latest developer version because _we can't always replicate the issues_. If we can't replicate the issues, we _HAVE_ to ask the user to test the fixes. How else do you expect us to verify the fix actually worked?

But at any rate, this has deviated from the point of this issue report. If you would like to discuss this further, join us on Discord and/or DM us. This is a place for reporting issues and making suggestions, not idle conversation.

**Comment by PedgeJameson** [comment]
I tried to ask about Discord, but you told me to leave the issue here. (suspicious)
As for testing, you give them source and they run through all this garbage. If you can't build test runs, then there is an issue. I am a tester for another front end and it's one man who does it. And it's builds, not source that has to go through loops.

And I think the devs at CEMU would love that quote.

**Comment by MrIlliteracy** [comment]
[Discord Invite](https://discord.gg/V73JuPF)

**Comment by PedgeJameson** [comment]
No, I have everything I need, don't try to lure me into your backtracking.

**Comment by MrIlliteracy** [comment]
> Don't get all pissy.

**Comment by RedDuckss** [comment]
```
I tried to ask about Discord, but you told me to leave the issue here. (suspicious)
```
You asked about Discord to report an issue. This is no longer an issue report, this is just you making idle conversation. Nearly every message from the past 2 days has had nothing to do with the issue report. I told you to take this to Discord because this is no longer about an issue.

```
As for testing, you give them source and they run through all this garbage. If you can't build test runs, then there is an issue.
```
It's 6 steps. There is no garbage. We can make builds. You clearly did not read my comment fully. I clearly said:

> We release alpha versions and ask people who have issues to try the latest developer version because we can't always replicate the issues. If we can't replicate the issues, we HAVE to ask the user to test the fixes.

We don't ask for users to test because we can't make builds, we do it because we cannot replicate the issue.

```
 I am a tester for another front end and it's one man who does it.
```
Then why are you here 🤔 (suspicious)

```
 And it's builds, not source that has to go through loops.
```
As does this. We just don't make builds for every single line change we make. That would be pointless and a waste of time.

**Comment by PedgeJameson** [comment]
I test for a multi emu launcher. Don't flatter yourself.
Good luck on this. See you on the next major CEMU patch.

**Comment by RedDuckss** [comment]
```
I test for a multi emu launcher. Don't flatter yourself.
```
How exactly were we "flattering" ourselves. All the information you gave was that you test another front end. Based on the context, we assumed you meant another Cemu front end. And even so, what part of my reply made it sound like we were flattering ourselves.

```
Good luck on this. See you on the next major CEMU patch.
```
I would love if Cemu made their own UI for games. The entire point of this project is to provide something that's missing, not sure why you keep using the idea of Cemu making their own as an insult. But there hasn't even been any conformation of Cemu making their own. In fact it _is_ confirmed that the next update will be a sound-only update. Not sure where you get this information from.

But again, and for the final time, this is no longer about this issue reported here or any issue/bug in general. So take this somewhere else, [like Discord](https://discord.gg/EKn8HnW), thanks.

Or, if you would like, instead of trying to throw aimless insults, you can either stop using this software (since you clearly don't like it and have a preference for the one you already test for. Which is fine, more power to you. Everyone has a preference, and we won't try and force you to use this software), or make _actual_ suggestions on how to improve rather than making rude comments which help nothing.

**Comment by PedgeJameson** [comment]
CEMU will have an interface that will scan the games you have on the drive and launch. So this will be obsolete once the interface lets you scan games. And no, I will not be in your Discord.

**Comment by RedDuckss** [comment]
```
CEMU will have an interface that will scan the games you have on the drive and launch. So this will be obsolete once the interface lets you scan games. 
```
Again, there has been no conformation of this anywhere. This is literally just speculation by you, with nothing to back it up. And if it does, I already said that's perfect. I clearly said before:

> I would love if Cemu made their own UI for games. The entire point of this project is to provide something that's missing, not sure why you keep using the idea of Cemu making their own as an insult.

```
And no, I will not be in your Discord.
```
Then stop talking about it here. Like I've said many times, this is _**not**_ the place for idle discussion. This is a place _to report bugs and issues_

**Comment by MrIlliteracy** [comment]
But for now, it's useful and that's why it exists. Since you don't want to join the discord to continue this conversation, I'll just close this issue as it was fixed but a new problem arose.
